# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table
# # see: https://terraform-docs.io/user-guide/configuration/version
version: ""
# see: https://terraform-docs.io/user-guide/configuration/header-from
header-from: docs/header.md
# see: https://terraform-docs.io/user-guide/configuration/footer-from
footer-from: ""
# see: https://terraform-docs.io/user-guide/configuration/recursive
# recursive:
#   enabled: false
#   path: modules
# see: https://terraform-docs.io/user-guide/configuration/sections
sections:
  hide: []
  show: []
# # see: https://terraform-docs.io/user-guide/configuration/content
content: |-
    {{ .Header }}

    ## Examples

    ```hcl
    {{ include "examples/basic/main.tf" }}
    ```

    {{ .Providers }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

    {{ .Resources }}
# # see: https://terraform-docs.io/user-guide/configuration/output
output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
# see: https://terraform-docs.io/user-guide/configuration/sort
sort:
  enabled: true
  by: name
# # https://terraform-docs.io/user-guide/configuration/output-values/
output-values:
  enabled: false
  from: ""
# see: https://terraform-docs.io/user-guide/configuration/settings
settings:
  anchor: false
  color: false
  default: true
  description: true
  escape: false
  hide-empty: false
  html: false
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true