name: Validate README.md
on:
  - pull_request
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and validate rendered file matches PR contents
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        config-file: .terraform-docs.yml
        fail-on-diff: true
