name: Terraform

on:
  pull_request:
    branches: [ master ]

env:
  TERRAFORM_VERSION: 1.0.9

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup terraform ${{ env.TERRAFORM_VERSION }}
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: terraform fmt
      run: terraform fmt -check

    - name: terraform init
      run: terraform init

    - name: terraform validate
      run: terraform validate